const {
		AddElement,
		AddElementValue,
		AddLeveledEntry,
		EditorID,
		FullName,
		GetElementFile,
		GetElement,
		GetElements,
		GetFileName,
		GetFlag,
		GetFormID,
		GetHexFormID,
		GetIntValue,
		GetLinksTo,
		GetMasterRecord,
		GetRecord,
		GetRecords,
		GetValue,
		GetWinningOverride,
		HasElement,
		HasKeyword,
		IsMaster,
		IsWinningOverride,
		RemoveElement,
		SetEnabledFlags,
		SetFormID,
		SetIntValue,
		SetLinksTo,
		SetValue
	} = xelib,
	{
		addProgress,
		copyToPatch,
		cacheRecord,
		loadRecords,
		logMessage
	} = helpers;